### ISSUE TITLE
Blocked IPs

### ISSUE THREAD

**Issue by Sikksens** [jamcalli/ABB-Discord-Bot#1]
Have you experienced ABB immediately blocking an IP after scraping? I am on NordVPN and it seems they are blocking every IP I change to.

**Comment by jamcalli** [comment]
Sometimes mirrors have pretty aggressive blocking protocols. I was constantly blocked for a while from a couple of them. I do not use a vpn for scraping and haven't had issues in many months. 

Try using [http://theaudiobookbay.se](http://theaudiobookbay.se)

This mirror seemed to never get blocked for me.

**Comment by Sikksens** [comment]
I did initially try that mirror too but used `https://` 
working great now, thank you :)
